name: bakerFi
networks:
- id: 8453
  start_block: 0
  contracts:
  - name: BaseVault
    address:
    - 0x37327c99bBc522e677a97d01021dB20227faF60A
    handler: src/EventHandlers.ts
    events:
    - event: AdminChanged(address previousAdmin, address newAdmin)
    - event: BeaconUpgraded(address indexed beacon)
    - event: Upgraded(address indexed implementation)
    - event: Deposit (address indexed sender, address indexed owner, uint256 assets, uint256 shares)
    - event: Transfer (address indexed from, address indexed to, uint256 value)
    - event: Withdraw ( address indexed sender, address indexed receiver,  address indexed owner, uint256 assets, uint256 shares)
    - event: FeeReceiverChanged (address feeReceiver)
- id: 42161
  start_block: 0
  contracts:
  - name: ArbitrumVault
    address:
    - 0x4c6d58749126FEBb1D28E8B8FdE97DC3107996d3
    handler: src/EventHandlers.ts
    events:
    - event: AdminChanged(address previousAdmin, address newAdmin)
    - event: BeaconUpgraded(address indexed beacon)
    - event: Upgraded(address indexed implementation)
    - event: Deposit (address indexed sender, address indexed owner, uint256 assets, uint256 shares)
    - event: Transfer (address indexed from, address indexed to, uint256 value)
    - event: Withdraw ( address indexed sender, address indexed receiver,  address indexed owner, uint256 assets, uint256 shares)
    - event: FeeReceiverChanged (address feeReceiver)
raw_events: true